# Generated by Django 5.2 on 2025-04-14 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='dislike_amount',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='like_amount',
        ),
    ]
